sudo: false
language: python
python: 2.7

branches:
 only:
   - master

 install:
   - pip install pep8
   - pip install coverage
   - pip install .

# Each step below must succeed for the build to pass
script:
    - coverage run --source=. test.py
    - coverage report -m
    - pep8 --format=pylint --count .
